### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by JonasCiss** [Darkhax-Minecraft/Enchanting-Plus#103]
I tried to compile a version fpr 1.12.2 but the build folder was not generated.

**Comment by FrancisDaPugtato** [comment]
There is a major bug which where it doesn't actually enchant in the incomplete system rn

But to build, I would get GIT CMD 
Then type `git clone https://github.com/Darkhax-Minecraft/Enchanting-Plus/`
When it clones do 'cd Enchanting-Plus', Then do 'git submodule init' and 'git submodule update'
Then, do 'gradle setupCIWorkspace build' Gonna take a while.

**Comment by FrancisDaPugtato** [comment]
Get Gradle, too
:D

**Comment by FrancisDaPugtato** [comment]
If it shows an error again, paste the error log in pastebin and post the link here so they can take a closer look at it.

**Comment by JonasCiss** [comment]
I used the script that already exist. There was a note on page of the source code.

**Comment by JonasCiss** [comment]
> If it shows an error again, paste the error log in pastebin and post the link here so they can take a closer look at it. 

He hadn't no error.

**Comment by FrancisDaPugtato** [comment]
Then its just your lack of finding the build folder then? I just did it and it worked- Its in the build/libs folder

**Comment by JonasCiss** [comment]
Would you mind giving me the complete path?

**Comment by JonasCiss** [comment]
Would you mind giving me the complete path?

**Comment by FrancisDaPugtato** [comment]
Your jar should be in Enchanting-Plus/Build/libs

**Comment by FrancisDaPugtato** [comment]
Make sure you're up to date.

**Comment by JonasCiss** [comment]
That folder wasn't generated. Which bug do you mean?
