### ISSUE TITLE
Reporting Missing Enchantments

### ISSUE THREAD

**Issue by NocturneBlock** [Darkhax-Minecraft/Enchanting-Plus#104]
Getting the message requesting that I report some missing enchantments in the 1.7.10 version.
enchantment.openblocks.flimflam
enchantment.me.leech
enchantment.me.wisdom
enchantment.me.poisonaspect
enchantment.me.slowaspect
enchantment.me.verticallity (sic)
enchantment.me.witheraspect
enchantment.me.greenwood
enchantment.me.disarm
enchantment.me.purging
enchantment.me.vigor
enchantment.me.heat
enchantment.me.edged
enchantment.openblocks.explosive
enchantment.openblocks.laststand
enchantment.me.antivenom
enchantment.me.horticulture
enchantment.me.nightvision
enchantment.me.photosynthesis
enchantment.me.regen
enchantment.me.magnet
enchantment.me.cloud
enchantment.me.steadfast
enchantment.me.swiftness
enchantment.me.highjump
enchantment.me.icestep

Looking at my mods list, "me" is probably More Enchantments. Let me know if there's any other information that would be helpful. :-)

**Comment by darkhax** [comment]
1.7.10 is over three years old and isn't receiving any updates. The format used in future versions has also changed, and I don't believe More Enchantments or OpenBlocks exists anymore. Thanks for reporting it still though.
