### ISSUE TITLE
Repair cost is broken

### ISSUE THREAD

**Issue by darkhax** [Darkhax-Minecraft/Enchanting-Plus#21]
The repair cost is extremely broken. In this test I tried to repair a stone shovel with efficiency I. The cost is 34 levels, but it should be 3-4 at most. 34 would only be acceptable if the durability being regained was much higher (like diamond), and the tool had 3-4 enchantments on it. 

![image](https://cloud.githubusercontent.com/assets/2250798/13196810/e588e984-d796-11e5-8692-af443a430c48.png)

**Comment by Zilacon** [comment]
Should have checked this sooner. We have been trying to figure out whats going on with this for 3 days. We thought it was some kind of mod conflict going on. Is there any ETA on when this would be fixed?

**Comment by O13SC3N3** [comment]
Seem to have a lot of players xp entirety taken even with a level 4, or even 24 levels of xp. Had one with 76 levels taken away with 6 levels needed to repair an item.

**Comment by O13SC3N3** [comment]
@darkhax Will this fix be implemented into the 1.7.10 version?

**Comment by darkhax** [comment]
Highly unlikely. At this point it is very difficult for me to work on 1.7.10 or backdate any of my projects. If you don't like the Enchanting plus 4 releases for 1.7.10 (I don't blame you if that is the case) you should try [this](http://minecraft.curseforge.com/projects/enchanting-plus/files/2218324) release. It still has a few minor bugs that were around from before I took over the project, but it is a lot more stable.
