### ISSUE TITLE
Enchants still missing

### ISSUE THREAD

**Issue by rastamanfb** [Darkhax-Minecraft/Enchanting-Plus#23]
This was said to be fixed in RC2 however it appears the config file problem is still apparent
https://github.com/Epoxide-MC/Enchanting-Plus/issues/13

I am using EnchantingPlus-1.7.10-4.0.0.74.jar and still encountering this problem
I have set B:useQuestMode=false and i am in survival but no enchantments show unless they already have been enchanted.
switching to creative mode shows all enchants

Regards

**Comment by rastamanfb** [comment]
any one able to look at this or has development closed on this project now?

**Comment by darkhax** [comment]
Sorry for not looking into this issue. My partner on the mod has completely abandoned MC modding, which puts me in a very difficult situation. I will have a look into the issue again when I get the chance.

**Comment by rastamanfb** [comment]
Thanks, its a shame as quite a lot of modpacks have moved from the old
eplus to this one. I appreciate its a hefty task and hope you can get back
on track.

**Comment by darkhax** [comment]
Just tested this on latest 1.9 and can confirm that this issue was fixed previously.

**Comment by rastamanfb** [comment]
Thanks, have you tested this on 1.7.10 though? I dont understand why this
would not be working and displays the same issue.

I will check with RC3 and get back to you

**Comment by rastamanfb** [comment]
tested and stilol doesnt work on 1.7.10 with RC3 of this version.
i am unable to build from the master as it gives errors but the one downloaded from curse certainly doesnt work.
please test this on 1.7.10 and not on new version of minecraft as the version i reported this for is 1.7.10

please see my config file 

# Configuration file

settings {
    # If this is true, players will be able to enchant items which are not at full durability. [default: true]
    B:allowDamagedEnchanting=true

    # If this is true, players will be able to disenchant enchanted items they come across. [default: true]
    B:allowDisenchanting=true

    # If true, special information will be written to the Scroll Modifier item tooltips. [default: true]
    B:allowModifierTooltips=true

    # If this is true, players will be able to repair damaged items at the advanced enchanting table, using experience points [default: true]
    B:allowRepairs=true

    # If enabled, players will be able to modify items which are not currently owned by any other player. IE: Dungeon Loot [default: true]
    B:allowUnownedModifications=true

    # If enabled, a custom E+ villager will spawn and generate in villages. [default: true]
    B:allowVillagers=true

    # A list of blacklisted enchantment ids. Each entry should be an integer. [default: ]
    S:blacklistedEnchantments <
     >

    # A list of blacklisted items and blocks. Things in this list won't be enchantable at the eplus table. The format is the same as minecraft's id system. For example, minecraft:chainmail_helmet will prevent chainmail helmets from becoming enchanted. [default: ]
    S:blacklistedItems <
     >

    # A number used when calculated enchantment cost. This number is treated as a % based factor. 0.30 = 30% of the original cost. 1.5 = 150% of the original cost. [range: 0.0 ~ 128.0, default: 1.0]
    S:costFactor=1.0

    # What is the maximum number of enchantments that could be applied at the Enchantment Table? [range: 0 ~ 4096, default: 5]
    I:maxEnchantmentAmount=5

    # The lowest number of bookshelfs required for the table to function properly. [range: 0 ~ 24, default: 5]
    I:minBookshelfs=5

    # The minimum amount of Bookshelfs required to use the enchantment table. [range: 0 ~ 64, default: 5]
    I:minimumBookshelfs=5

    # Should the table restrict the level of effects based on the amount of bookshelves? [default: true]
    B:needBookshelves=true

    # If true, Enchanting Plus will ocasionally write messages to the console. [default: true]
    B:printDebug=true

    # A number used when calculating the repair costs. A higher factor means higher repair costs. [range: 0 ~ 128, default: 5]
    I:repairFactor=5

    # The percent chance that a hostile mob should drop a scroll. Default is 0.01 which is 1% [range: 0.0 ~ 1.0, default: 0.01]
    S:scrollDropRate=0.5

    # If enabled, players will only be able to enchant enchanted items if they enchanted them first. [default: true]
    B:secureItems=false

    # Quest Mode requires that users collect scrolls to unlock enchantments, before they can make use of them at the table. [default: true]
    B:useQuestMode=false

    # A unique ID for the E+ villager. This should almost never need to be changed. [range: -2147483648 ~ 2147483647, default: 935153]
    I:villagerID=935153
}

**Comment by darkhax** [comment]
Your config file looks fine. Are you putting a tool in the table?

**Comment by rastamanfb** [comment]
Any weapon or tool. Diamond sword for example will not show any enchants
available unless i enable creative mode or i cheat in some scrolls and eat
them to learn the enchant.

Basically it seems its ignoring that value in the config.

**Comment by darkhax** [comment]
That is very strange. Since you do not want to use the enchantment scrolls I would highly recommend sticking to the Enchanting Plus 3 for 1.7.10. Since I can not go back and make any changes to 1.7.10 I am going to hide all of the experimental alpha releases.

**Comment by rastamanfb** [comment]
Ahh ok, the reason i highlighted this is because one of technic launchers
biggest packs: The 1.7.10 pack uses this version of eplus and thus when
upgraded i was forced to use this version. It was added due to some
conflicts the old eplus had. I was hoping that this fault could be fixed. I
guess youve moved on to newer versions on minecraft.
http://www.technicpack.net/modpack/the-1710-pack.453902

**Comment by darkhax** [comment]
That's really unfortunate. You should ask them to revert to the old version. Not sure why they would update to an alpha release of the mod and expect it to be stable.

**Comment by rastamanfb** [comment]
They probably liked the idea of scrolls as it ties in with some of the
questing features of the modpack.
For some of us though we just like to explore and try stuff and the used
eplus as it was as it fot with the way we play the modpack.
Ahh well, ill let the modpack curator know and see what he does with it.

Thanks for Responding so rapidly
