### ISSUE TITLE
Config options being ignored?

### ISSUE THREAD

**Issue by Kiyaku** [Darkhax-Minecraft/Enchanting-Plus#24]
Heya,

i made some changes to the config file but i get the feeling that a lot or all of it is being ignored. 
I deleted the old file and let the game generate one again, just to make sure its up to date and the right file (it's in config/eplus.cfg). 

Version is EnchantingPlus-1.7.10-4.0.0.74

These are my changes: http://pastebin.com/LBHeHfGY 

The two blacklisted enchantments are Luck of the Sea and Lure. I still see Luck of the Sea but not Lure.

Disenchanting is disabled but i can still disenchant any loot i found. 

The blacklisted items are all fishing rods in my pack. I can still enchant all of them. 

Any idea?

**Comment by Kiyaku** [comment]
Actually sorry, the commas shouldnt be there, if i remove them the blacklist works, my bad. 

Disabled repair seems to work too, but the Disenchanting option still seems to be ignored. 

Is it possible to remove the Vanilla button from the UI too so the user HAS to use the advanced table? (i remove the recipe for the vanilla table).

**Comment by darkhax** [comment]
1.7.10 is not being supported, although a few of these issues did exist in newer versions and have been adressed.

**Comment by Kiyaku** [comment]
Well it's a 6 months old ticket haha, but i'm really happy to see this mod being out for 1.10 now :D 
Thanks for all the work!
