### ISSUE TITLE
[1.9] Crash on launch with version 1.9-4.1.0.94

### ISSUE THREAD

**Issue by CA2020** [Darkhax-Minecraft/Enchanting-Plus#26]
Whenever I try to launch using this version, the pack crashes.

http://pastebin.com/gcK1ekx5

**Comment by darkhax** [comment]
You need to use the latest version of Bookshelf. [This](http://minecraft.curseforge.com/projects/bookshelf/files/2295880) is the current required version.

**Comment by CA2020** [comment]
Thanks a lot, gonna check that. I didn't updated because when I launch without the Bookshelf API it asked for an older one to the one I was using. Thanks for the heads up ;)
