### ISSUE TITLE
Files Config Fail ! 

### ISSUE THREAD

**Issue by FredericFernandes** [Darkhax-Minecraft/Enchanting-Plus#30]
Good evening,I contact you because I have a problem with your mods ! Already I do not speak too very well English ...

That is why I am going to make simple.
We fully agree that we have two files config one for the waiter(server) and an other one for the customer, but the problem and that we can modify the customer config to activate for example the repair which it is deactivated side waiter(server),I would like to know how is that we cannot change the config only customer side.

Thank you.

**Comment by darkhax** [comment]
Typically when you distribute your mod pack you give out the config files along side the mod files. This ensures that both will have the same settings. The client will still be able to change their config file, and there is nothing you can do to force them to change it back. For the majority of things which are handled on the server, like the player being able to repair an item, the server config file is the only one checked.

**Comment by FredericFernandes** [comment]
And We can't check the client file ?

**Comment by darkhax** [comment]
No you can not check what the client has in their configuration file. This is largely because the client side configuration file is completely irrelevant to code that is running on the server.
