### ISSUE TITLE
1.9.4 version is actually 1.9...

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/Enchanting-Plus#31]
The latest 1.9.4 version is not actually that version.  It's 1.9 and minecraft will not launch.

**Comment by MokahTGS** [comment]
https://dl.dropboxusercontent.com/u/9882100/Minecraft/ep.jpg

**Comment by darkhax** [comment]
Thank you for reporting the issue, forgot to upload the version number changes for 1.9.4.
