### ISSUE TITLE
Why no more beta versions of the 1.7.10 branch?

### ISSUE THREAD

**Issue by xJon** [Darkhax-Minecraft/Enchanting-Plus#35]
Topic pretty much sums it up.
But you'll be surprised by how many players still play [1.7.10](http://www.technicpack.net/modpack/the-1710-pack.453902).

**Comment by darkhax** [comment]
The progress for this mod is significantly lowered with every version of Minecraft that I target.To deal with this, I have opted to support the "best" version of the game. While 1.7.10 still has a large player base, that doesn't really count for anything when deciding whether or not to target it. 1.7.10 is a few years outdated, and it definitely shows. It has several huge performance and security issues, along with an endless laundry list of bugs. 

I get that it may be hard to use newer versions of the mod, as other essential mods are not available for the latest versions of MC, however supporting deprecated versions of MC is not the best thing for the mod community. Instead, you should be encouraging other mod authors to update, and contribute to possible alternatives. (Like JEI as an alternative to NEI)

**Comment by xJon** [comment]
So would you not recommend me to keep the beta 4 of the mod in my modpack?

**Comment by darkhax** [comment]
It depends on if you like the content in the beta. It wont be receiving any updates, so you will be stuck with the bugs you find. There is a stable version up on Curse as well that is not part of the beta.

**Comment by xJon** [comment]
That's unfortunate. Thanks for replying.
