### ISSUE TITLE
Crash Report 1.9 New WorldGen

### ISSUE THREAD

**Issue by RaineAndrews** [Darkhax-Minecraft/Enchanting-Plus#36]
Minecraft 1.9.4
Forge 12.17.0.1987
Enchanting Plus 4.1.0.101

[fml-client.log.zip](https://github.com/Darkhax-Minecraft/Enchanting-Plus/files/333351/fml-client.log.zip)

Can you speak crashlog? If you identify an incompatibility, I can try to disable that mod instead to check :)

**Comment by darkhax** [comment]
This is a duplicate of #34 please look there for more info.
