### ISSUE TITLE
Suggestion - Make config option to disable scrolls and use old system

### ISSUE THREAD

**Issue by psychofad** [Darkhax-Minecraft/Enchanting-Plus#37]
I am a server owner and would like to have the option to use the Advanced Enchantment Table the way it was originally intended.  Sure the adventure aspect of finding scrolls may be a novelty, but if a server is employing any kind of world border this becomes moot real quick.  Additionally, hoping that eventually a mob may possibly drop the one enchantment you are looking for seems to remind me of the RNG nightmare that plagues most MMORPG games, no thank you.  

A simple config option for those of us that just want an OP enchantment table would be great, otherwise, it becomes as random as it's vanilla counterpart. 

I appreciate you continuing this mod, but you know what they say, if it ain't broke....

**Comment by darkhax** [comment]
There is already a configuration option for this, it's called useQuestMode. That said, if you're on 1.7.10, the beta builds are all marked as unstable and should not be used for serious play. There latest 1.7.10 on CurseForge is the -d version which was made long before the quest system was put in place. If you're using this on 1.8/1.9 all available downloads are unstable alpha and will probably crash you if you decide to use them.
