### ISSUE TITLE
The state of Enchanting Plus

### ISSUE THREAD

**Issue by 63502** [Darkhax-Minecraft/Enchanting-Plus#38]
I am a bit concerned about the state of Enchanting Plus at this time. Since enchanting plus is the only mod of its kind that I have ever been able to find, and it provides one of the most useful mechanics in the game, I have included it into almost every mod setup I have used since early 1.7.10. I have been looking forward to a 1.9.4/1.10.X compatible version that is actually playable, but unfortunately the Eplus Github page has been inactive and more or less untouched for at least a month if not more.

Has this mod been discontinued?
If yes, do you know of any other mods that do the same or close to the same thing that eplus does that work in minecraft version 1.10.2?
(other than EnderIO)

Thanks,
     63502

**Comment by LemADEC** [comment]
Eplus behavior is fairly "OP". Other mods provide more complex setup to choose your enchants, for example Botania.

**Comment by darkhax** [comment]
@LemADEC I strongly disagree with that statement. I would go as far to say that E+'s enchanting system is under powered when compared against vanilla's enchanting system. For example, the highest level cost for an enchantment under the vanilla system is 3 levels. Compared to the E+ system, 3 levels for an enchantment is extremely cheap, and would at most get you 1 level of a basic enchantment. On average, the player will spend significantly more EXP on enchanting when using the E+ system. I think that is a fair exchange for the option of choice, which is what E+ offers. It's also worth noting that the vanilla system now gives players a hint on the enchantments they will receive, so even the power of choice is not the same as it once was. And then you have the scroll system, which prevents players from just adding any enchantment they like, without first exploring.

**Comment by darkhax** [comment]
@63502 E+ is still being maintained, however progress has significantly slowed. This is largely due to one of the core team members leaving the project due to college taking up too much time. The 1.8, 1.9 and 1.10 updates have all come changes to the enchanting system which also seriously impact progress. A lot of the internal systems need to be completely overhauled for the 4th time now, since I have taken on the project. A proper update is coming, however it will take some times.

**Comment by 63502** [comment]
Ok, good to know that you are still maintaining the mod. Thanks for responding, and I look forward to the next update, whenever it may be.

**Comment by 63502** [comment]
> A proper update is coming, however it will take some times.

"Times"? W.D. Gaster much? XD

**Comment by darkhax** [comment]
I will be using #32 to note the progress of the next release.
