### ISSUE TITLE
Don't own the item I just enchanted?

### ISSUE THREAD

**Issue by paustin123** [Darkhax-Minecraft/Enchanting-Plus#39]
I'm not running a cracked version I bought this. Im using the 1.7.10 pack on technic. Ive disabled both lines of code:     
![screenshot_15](https://cloud.githubusercontent.com/assets/20675776/17165210/6e043236-5394-11e6-93ad-b2661ebe2b9c.png)
![screenshot_16](https://cloud.githubusercontent.com/assets/20675776/17165211/6e07e0b6-5394-11e6-9cdd-fd533cacb942.png)
# If enabled, players will be able to modify items which are not currently owned by any other player. IE: Dungeon Loot [default: true]
    B:allowUnownedModifications=false

# If enabled, players will only be able to enchant enchanted items if they enchanted them first. [default: true]
    B:secureItems=false
They are disabled on client + server and I've tried different combinations. It doesnt work.

**Comment by paustin123** [comment]
Ok so I downloaded K cauldron and ran that to grab some functions like /home and it seems to have fixed it that way. So.

**Comment by darkhax** [comment]
The whole ownership idea is being scrapped. It seems to cause a lot of problems for cracked users, and players running on different server types.
