### ISSUE TITLE
/help throws an error

### ISSUE THREAD

**Issue by mntnoe** [Darkhax-Minecraft/Enchanting-Plus#40]
The /help command throws the following error on 3.0.2-d (1.7.10):

```Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"clickEvent":{"action":"suggest_command","value":"/eplus"}} into a Component```

**Comment by darkhax** [comment]
1.7.10 is not a supported version.
