### ISSUE TITLE
Bugs and a question.

### ISSUE THREAD

**Issue by 63502** [Darkhax-Minecraft/Enchanting-Plus#46]
The bug:

- Enchantment table breaks instantly with any item or empty hand, and only drops as an item if broken with a pickaxe.

The question:

- When I have the config file set so the table does not need bookshelves to add higher cost enchants, the table still requests more bookshelves anyway. Is this a bug, or am I just missing another setting elsewhere?

Eplus Version: EnchantingPlus-1.10.2-4.1.0.112
Thanks,
     63502

**Comment by darkhax** [comment]
Thank you for reporting this issue. As for your question, that is likely a bug. I will be going through all of the config options once again to test if they work as expected.
