### ISSUE TITLE
empty config file, no documentation

### ISSUE THREAD

**Issue by Maccool** [Darkhax-Minecraft/Enchanting-Plus#53]
I was looking into making some config changes to the file "eplus.cfg" (this is the enchanting plus config, right?), but it is completely empty. I went looking for some form of documentation here and in the eplus forum threads on the minecraft and curse forums. A link or something to config docs or setting all the defaults in the config with comments would be great.

MC version 1.8, forge 1.8-11.14.4.1577, liteloader 1.8-1.8

**Comment by darkhax** [comment]
The 1.8 version of the mod is not stable for gameplay. The config options are not there, because they have not been implemented for that version. The only stable version since 1.7.10 is the latest non alpha release for 1.10.2.

**Comment by Maccool** [comment]
The problem for me is that, while I've moved on past MC1.7, many of the mods I like to use are not updated for MC1.10. MC1.8 is about the right compromise at the moment. EPlus 1.8 has played alright for a couple of weeks without config changes so I'll probably continue on using it.  Barring the availability of 1.8 documentation, I'll set up a 1.7 game to get a look at the config and see what actually works for 1.8
