### ISSUE TITLE
Balance/Enhancement request

### ISSUE THREAD

**Issue by ariosos** [Darkhax-Minecraft/Enchanting-Plus#54]
1 - Since modern Minecraft enchanting uses Lapis, there should be a slot for requiring lapis, or other items for enchanting (config option).
2 - Mending is kind of an end-game enchant. This is where the above item slot would come in, and should require a Dragon Egg (as you can now respawn the dragon), or some other item from the End.
3 - Mending should be a lot more than just 18 levels...

**Comment by darkhax** [comment]
1) Modern mc also costs 1-3 levels per enchantment. Wouldn't you say that the large amount of EXP in difference more than makes up for that material cost?

2) You still need to find the mending scroll if you play with the default config options. Also mending isn't as end game as you make it out to be. It is possible to get mending through vanilla play long before you even visit the nether. 

3) 18 levels is a fair bit. If you can reliably get that much EXP (mob grinder or good enough mining setup) you're at the point in the game where mending should be available.
