### ISSUE TITLE
[1.10.2] Client Crash repairing armor without enough XP

### ISSUE THREAD

**Issue by Morpheus1101** [Darkhax-Minecraft/Enchanting-Plus#55]
server console spammed this information https://puu.sh/shIDK/5521d7251b.txt

**Comment by TheRealDadbeard** [comment]
I have the same issue but it think it happens randomly. After that the item is lost.

http://txt.do/d57ex

**Comment by lucom** [comment]
Same issue here when repairing random stuff on a server.

According to issues mentioned in other mods (https://github.com/raoulvdberge/refinedstorage/issues/106) this happens when calling client stuff on the server...

**Comment by xaleb** [comment]
Game ate my crap when trying to use repair function on advanced enchantment table. Latest 1.10. Just like everyone else here. Please tell me you are one of those authors to develop for the most popular version..and not just the latest..lol. Can you fix it?
