### ISSUE TITLE
Compatibility with mod's armor/weapons?

### ISSUE THREAD

**Issue by DoomSquirter** [Darkhax-Minecraft/Enchanting-Plus#57]
if the eplus table won't accept an item, but [u]ses in JEI show it enchantable, is the compatibility issue in eplus or the other mod?

example: 
RedstoneFluxArsenal-[1.10.2]-1.0
EnchantingPlus-1.10.2-4.1.0.115

redstone flux arsenal's armor shows lots of uses in jei but the pieces won't drop into the eplus table at all.

OTOH, I was quite suprised to see enchants for the exu2 boomerang and the boomerang itself goes into the eplus table just fine, so I'm leaning towards the 'other mod' theory.

**Comment by darkhax** [comment]
Yes, other mods and enchantments from other mods are supported by E+. Note that some items may be enchantable but not at an enchanting table, and some enchantments can only be applied to certain items.
