### ISSUE TITLE
Minecraft Crash on "/help x"

### ISSUE THREAD

**Issue by svalcken** [Darkhax-Minecraft/Enchanting-Plus#58]
Hello,

i have minecraft 1.7.10 with forge 10.13.1.1640. After installation of Enchanting-Plus 3.0.1-d the ingame command /help crashes the minecraft on show the "/eplus" command.

i can reproduce it with a fresh installation from minecraft and forge.

**Comment by darkhax** [comment]
1.7.10 is over two years old and is no longer supported.
