### ISSUE TITLE
Enchanting Plus work only in creative

### ISSUE THREAD

**Issue by BobTheGamer** [Darkhax-Minecraft/Enchanting-Plus#65]
I use Enchanting Plus 1.8-3.1.0a1 for minecraft 1.8, when ever im in survival i am unable to enchant tools, creative i can however, i heard about scrolls but they are not ingame. please help, i love this mod

**Comment by darkhax** [comment]
The scrolls 100% are in game. Look in the creative tab if you can't find them in JEI.

**Comment by BobTheGamer** [comment]
they are not, check the version
