### ISSUE TITLE
No Survival Enchanting

### ISSUE THREAD

**Issue by BobTheGamer** [Darkhax-Minecraft/Enchanting-Plus#67]
Hi, i use this mod for 1.8 and am only able to enchant with it while in creative mode, whenever i am in survival the enchants will appear but when i have the levels set and i click enchant it doesn't work.

**Comment by Revvilo** [comment]
Do you have enough experience or enough bookshelves placed around the table?
It should display any problems on the left if I remember rightly.

**Comment by BobTheGamer** [comment]
i have enough xp and it never said anything about bookshelfs, i will try tomorrow after school

**Comment by BobTheGamer** [comment]
it was the need for book selfs thank you very much 👍 :)
