### ISSUE TITLE
[1.10.2] Client Crash trying to generating world

### ISSUE THREAD

**Issue by Morpheus1101** [Darkhax-Minecraft/Enchanting-Plus#71]
https://puu.sh/wfbMA/667326f3ef.log

**Comment by darkhax** [comment]
```
Caused by: java.lang.NullPointerException
	at net.darkhax.eplus.item.ItemScroll.enchantScroll(ItemScroll.java:58) ~[ItemScroll.class:?]
	at net.darkhax.eplus.item.ItemScroll.createScroll(ItemScroll.java:47) ~[ItemScroll.class:?]
	at net.darkhax.eplus.item.ItemScroll.func_150895_a(ItemScroll.java:119) ~[ItemScroll.class:?]
	at crazypants.enderio.integration.jei.ItemHelper.getValidItems(ItemHelper.java:24) ~[ItemHelper.class:?]
	at crazypants.enderio.integration.jei.DarkSteelUpgradeRecipeCategory.<clinit>(DarkSteelUpgradeRecipeCategory.java:67) ~[DarkSteelUpgradeRecipeCategory.class:?]
	... 41 more
```

**Comment by Morpheus1101** [comment]
https://github.com/Darkhax-Minecraft/Enchanting-Plus/blob/master/src/main/java/net/darkhax/eplus/item/ItemScroll.java#L58

enchantment.getRegistryName() can be null

i could be wrong but....well yeah

**Comment by darkhax** [comment]
It shouldn't ever be null. Enchantments with null registry names are still adding enchantments the 1.7.10 way and need to fix it. Looking through the code, that doesn't seem to be the specific issue here though.

**Comment by Morpheus1101** [comment]
Was the problematic mod every found with this issue or was it E+ and being 1.10.2 is no longer being supported?

**Comment by darkhax** [comment]
Unfortunately not. The code for 1.12 had many built in checks to detect and identify these, without causing crashes.

**Comment by Morpheus1101** [comment]
This was something i re-occured using 1.10.2 which as a side note also cause JEI to stop functioning .. While i did not do extensive tests, by disabling E+ this resolved the issue of JEI not working in SP & SMP but also allowed a SP World to be loaded.  But also being 1.10.2 i wasnt sure if the version is still supported

**Comment by yesterday17** [comment]
@Morpheus1101 
Since this mod doesn't have a open source license, it's all right rights reserved by default(see github's tos). But i don't whether it's permitted to share this built version of Enchanting Plus. So if there's any problem, @darkhax please tell me and i'll remove it.

[Dropbox](https://www.dropbox.com/sh/3nyr3753zhqkpo3/AAA7JNd618_Gc65CeGpvZaPia?dl=0)

**Comment by darkhax** [comment]
I have no issue with you sharing this particular version here. Just don't include it in any publicly distributed mod packs, or pass it off as an official or supported version.

**Comment by Morpheus1101** [comment]
Its ok i just removed E+ from the public pack .. it was only 1.10.2 and the last update to the pack and im actively developing a 1.12.2 pack now.  thanks anyway
