### ISSUE TITLE
A Bug in Version 3.0.2-d with MC 1.7.10

### ISSUE THREAD

**Issue by svalcken** [Darkhax-Minecraft/Enchanting-Plus#76]
Hello,

i known, this is a old version of mod.
I have the problem with Life in the Woods, This can only run on 1.7.10. I have a bug in the Version 3.0.2-d from Enchanting-Plus.
On use the Helppages in MC Client, the client crashes on Site with the mod. I have testet and the enchanting-plus 3.0.2-d mod is the problem.
I have allready seen only the version 4 is here to find.

Here I will ask, if anybody has the source code of 3.0.2-d? I will try to fix self the bug,

Can you help?

**Comment by darkhax** [comment]
I don't believe the source code is public anymore, however you can use the Bearded Octo Nemesis tool to deobfuscate the mod source code.
