### ISSUE TITLE
What Happened to the 1.7.10 dev versions?

### ISSUE THREAD

**Issue by TomShkurti** [Darkhax-Minecraft/Enchanting-Plus#77]
I'm seeing deobf versions for 1.10.2 and 1.9.4, but nothing older than that. I remember 1.7.10 dev versions existing, though...

**Comment by darkhax** [comment]
The 1.7.10 dev versions were for E+ 4. Version 4 was in a very early alpha, and had many game breaking bugs. We moved on to 1.8+ for the alpha but people were still downloading the broken 1.7.10 version instead of the stable 1.7.10 build. So we removed those alpha builds from the curse page.
