### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by KrauzeBartek** [Darkhax-Minecraft/Enchanting-Plus#80]
When will be E-Plus for mc 1.11.2 and 1.12.2 ?

**Comment by darkhax** [comment]
E+ is still being worked on, however I haven't had enough consecutive time to sit down and give it a good push. I am hoping to have an actual playable release out before the end of the year, and it will be for whatever version I am targeting with the rest of my mods at the time. Currently it looks like that will be 1.12.2.
