### ISSUE TITLE
Multishot Learned but no Application

### ISSUE THREAD

**Issue by frakier** [Darkhax-Minecraft/Enchanting-Plus#81]
1.10.2 learned multishot but cannot use it on a bow. Is it even for bows?
Hate that I am basically asking a question here but could not find anywhere else to ask.
Thanks for your time.

**Comment by darkhax** [comment]
I have no clue, and this isn't the place to ask. It's probably [this](https://teamcofh.com/docs/multishot/) though.

**Comment by frakier** [comment]
Wait... So I have a scroll added by Enchanting Plus - Enchantment: Multishot buts this is the wrong place to ask? So does Enchanting Plus just create a scroll for any spell in the system? OK...I'll go check out your link.
